### PR TITLE
[WIP] first move from legacy to aten native

### PR DESCRIPTION
**Pull request by xmnlab**
basically at this moment was just removing code ...

### CODE REVIEW

**Comment by xmnlab** [comment]
@hameerabbasi 

if it makes sense for you, could you rebase and merge it? (this PR just send to our branch issue10482-reduce-code-duplication)

**Comment by hameerabbasi** [comment]
It looks fine so far, but I'd like to add ATen as well before merging. :)

**Comment by xmnlab** [comment]
Sounds good @hameerabbasi 
feel free to work on issue10482-xmn branch :)

@fmassa do you have any feedback for this initial work?

**Comment by hameerabbasi** [comment]
@xmnlab Is the new code added to a header, and is the header included in the `CMakeLists.txt` file?

**Comment by fmassa** [comment]
Hi @xmnlab,

I think that this first step sounds reasonable.

I was also thinking that for the ATen implementation, we might want to have a single main entry-point `interpolate`, instead of 20 different functions in the main namespace.

In order to make this simple, what about just prefixing the current `ATen` implementations with an `_` to show that they are private, and then expose the `interpolate` which calls into them?

Thoughts?

cc @ezyang

**Comment by ezyang** [comment]
I'm not too sure what is going on here, but if you can in fact delete this code, that's fine. But I suspect there's more to do?

**Comment by xmnlab** [comment]
@fmassa @ezyang thanks for the feedback.

@ezyang yes it is just a initial work on an internal branch (quansight) before we open a PR into pytorch. I am working now moving the code for ATen.

thanks!

**Comment by xmnlab** [comment]
I moved and join CU files from THCUNN and THCUNN/generic to ATen/native/cuda ... my next step would be work on each CU file (because I just join the code to help the organization)

**Comment by fmassa** [comment]
Sounds good @xmnlab 

One thing I think I mentioned in the slack, there is an ATen equivalent for the `THCDeviceTensor`, which is called [`PackedTensorAccessor`](https://github.com/pytorch/pytorch/blob/4404762d7dd955383acee92e6f06b48144a0742e/aten/src/ATen/core/TensorAccessor.h), which I believe is equivalent to `THCDeviceTensor`.

We also have a CPU version of it, which could be used to make the kernels more generic if possible, but I'm not sure how it will play out if we use an arbitrary number of dimensions for interpolate, as those structs require a compile-time number of dimensions to be indexed.

**Comment by hameerabbasi** [comment]
@fmassa We decided in an internal meeting that @xmnlab would handle the move to ATen, and I'd handle moving the algorithm over to the pattern described in the issue, which specifies the interpolation method and the axes to interpolate over. @asmeurer would help review everything. 🙂

**Comment by xmnlab** [comment]
it seems that `rebase` confused` github`. I will close this PR and open a new one.

**Comment by fmassa** [comment]
@xmnlab I usually do
```
git pull --rebase origin master
```
and it usually works fine.

**Comment by xmnlab** [comment]
thanks @fmassa !

I did `git fetch upstream && git rebase -i upstream/master`

where my upstream is:

```
upstream        https://github.com/pytorch/pytorch.git (fetch)
upstream        https://github.com/pytorch/pytorch.git (push)
```

not sure why it doesn't work ... it seems the target branch was fixed to some point (commit) in the github history ...

I am working now on https://github.com/Quansight/pytorch/pull/2

**Pull request closed without merging**
